access_token: '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'

directories:
  datasets: 'datasets'
  models: 'models'
  prompt: 'utils/prompt.txt'

log_level: 'DEBUG'

firebase_creds: 'utils/parcours-creds.json'